namespaceOverride: microshop
createNamespace: false

config:
  POSTGRES_HOST: 192.168.1.16
  POSTGRES_PORT: "5432"
  POSTGRES_DB: microshop
  POSTGRES_USER: microshop
  REDIS_URL: redis://redis:6379/0
  KAFKA_BOOTSTRAP_SERVERS: kafka-broker-0.kafka-broker-headless.kafka.svc.cluster.local:9092

secret:
  POSTGRES_PASSWORD: microshop
  JWT_SECRET: supersecret

redis:
  image: redis:7-alpine

services:
  auth-service:
    image: ghcr.io/pascariucosmin93/magazon/auth-service:latest
    containerPort: 8000
    servicePort: 8000
    serviceType: ClusterIP
    replicas: 1
  product-service:
    image: ghcr.io/pascariucosmin93/magazon/product-service:latest
    containerPort: 8000
    servicePort: 8000
    serviceType: ClusterIP
    replicas: 1
  cart-service:
    image: ghcr.io/pascariucosmin93/magazon/cart-service:latest
    containerPort: 8000
    servicePort: 8000
    serviceType: ClusterIP
    replicas: 1
  order-service:
    image: ghcr.io/pascariucosmin93/magazon/order-service:latest
    containerPort: 8000
    servicePort: 8000
    serviceType: ClusterIP
    replicas: 1
  inventory-service:
    image: ghcr.io/pascariucosmin93/magazon/inventory-service:latest
    containerPort: 8000
    servicePort: 8000
    serviceType: ClusterIP
    replicas: 1
  payment-service:
    image: ghcr.io/pascariucosmin93/magazon/payment-service:latest
    containerPort: 8000
    servicePort: 8000
    serviceType: ClusterIP
    replicas: 1
  notification-service:
    image: ghcr.io/pascariucosmin93/magazon/notification-service:latest
    containerPort: 8000
    servicePort: 8000
    serviceType: ClusterIP
    replicas: 1
  frontend:
    image: ghcr.io/pascariucosmin93/magazon/frontend:latest
    containerPort: 80
    servicePort: 80
    serviceType: NodePort
    nodePort: 30080
    replicas: 1
