config:
  POSTGRES_HOST: 192.168.1.16
  KAFKA_BOOTSTRAP_SERVERS: kafka.kafka.svc.cluster.local:9092

services:
  auth-service:
    tag: 0.0.44
  product-service:
    tag: 0.0.44
  cart-service:
    tag: 0.0.44
  order-service:
    tag: 0.0.44
  inventory-service:
    tag: 0.0.44
  payment-service:
    tag: 0.0.44
  notification-service:
    tag: 0.0.44
  frontend:
    tag: 0.0.44
    serviceType: LoadBalancer
    loadBalancerIP: 10.10.2.50
