namespaceOverride: microshop
createNamespace: false

config:
  POSTGRES_HOST: 192.168.1.16
  POSTGRES_PORT: "5432"
  POSTGRES_DB: microshop
  POSTGRES_USER: microshop
  REDIS_URL: redis://redis:6379/0
  KAFKA_BOOTSTRAP_SERVERS: kafka.kafka.svc.cluster.local:9092

secret:
  POSTGRES_PASSWORD: microshop
  JWT_SECRET: supersecret

redis:
  image: redis:7-alpine

services:
  auth-service:
    repository: ghcr.io/pascariucosmin93/magazon/auth-service
    tag: 0.0.2
    containerPort: 8000
    servicePort: 8000
    serviceType: ClusterIP
    replicas: 1
  product-service:
    repository: ghcr.io/pascariucosmin93/magazon/product-service
    tag: 0.0.2
    containerPort: 8000
    servicePort: 8000
    serviceType: ClusterIP
    replicas: 1
  cart-service:
    repository: ghcr.io/pascariucosmin93/magazon/cart-service
    tag: 0.0.2
    containerPort: 8000
    servicePort: 8000
    serviceType: ClusterIP
    replicas: 1
  order-service:
    repository: ghcr.io/pascariucosmin93/magazon/order-service
    tag: 0.0.2
    containerPort: 8000
    servicePort: 8000
    serviceType: ClusterIP
    replicas: 1
  inventory-service:
    repository: ghcr.io/pascariucosmin93/magazon/inventory-service
    tag: 0.0.2
    containerPort: 8000
    servicePort: 8000
    serviceType: ClusterIP
    replicas: 1
  payment-service:
    repository: ghcr.io/pascariucosmin93/magazon/payment-service
    tag: 0.0.2
    containerPort: 8000
    servicePort: 8000
    serviceType: ClusterIP
    replicas: 1
  notification-service:
    repository: ghcr.io/pascariucosmin93/magazon/notification-service
    tag: 0.0.2
    containerPort: 8000
    servicePort: 8000
    serviceType: ClusterIP
    replicas: 1
  frontend:
    repository: ghcr.io/pascariucosmin93/magazon/frontend
    tag: 0.0.2
    containerPort: 80
    servicePort: 80
    serviceType: LoadBalancer
    replicas: 1
