apiVersion: v1
kind: ConfigMap
metadata:
  name: microshop-config
  namespace: {{ include "microshop.namespace" . }}
data:
  POSTGRES_HOST: {{ .Values.config.POSTGRES_HOST | quote }}
  POSTGRES_PORT: {{ .Values.config.POSTGRES_PORT | quote }}
  POSTGRES_DB: {{ .Values.config.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.config.POSTGRES_USER | quote }}
  ADMIN_EMAIL: {{ .Values.config.ADMIN_EMAIL | quote }}
  REDIS_URL: {{ .Values.config.REDIS_URL | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.KAFKA_BOOTSTRAP_SERVERS | quote }}
  PUBLIC_BASE_URL: {{ .Values.config.PUBLIC_BASE_URL | quote }}
