apiVersion: v1
kind: Secret
metadata:
  name: microshop-secret
  namespace: {{ include "microshop.namespace" . }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | quote }}
