apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: microshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: microshop/payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: SERVICE_NAME
              value: payment-service
          envFrom:
            - configMapRef:
                name: microshop-config
            - secretRef:
                name: microshop-secret
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: microshop
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
